name: Build and Publish NuGet Package

# on:
#   push:
#     tags:
#       - 'v*.*.*' # Triggers on version tags like v1.0.0

on:
  push:
    branches:
      - main  # Adjust the branch name as necessary

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore DotnetStandardSDK/DotnetStandardSDK.sln

      - name: Build the solution
        run: dotnet build DotnetStandardSDK/DotnetStandardSDK.sln -c Release

      # Uncomment if you want to run tests
      # - name: Test the solution
      #   run: dotnet test --configuration Release --no-build

      - name: Pack the NuGet package
        run: dotnet pack DotnetStandardSDK/DotnetStandardSDK/DotnetStandardSDK.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish the package to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source GitHubPackages --api-key ${{ secrets.GITHUB_TOKEN }}
