name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

permissions:
  contents: read
  packages: write  # Ensure the token can push packages
  # Add permission for user info access
  user: read # Adds permission for accessing user-related data

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test GitHub Token Validity
        run: |
          echo "Testing GitHub token validity... ${{ secrets.GITHUB_TOKEN }}"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Add GitHub Packages to NuGet sources
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -n GitHubPackages --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore DotnetStandardSDK/DotnetStandardSDK.sln

      - name: Build the solution
        run: dotnet build DotnetStandardSDK/DotnetStandardSDK.sln -c Release

      - name: Pack the NuGet package
        run: dotnet pack ./DotnetStandardSDK/DotnetStandardSDK/DotnetStandardSDK.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish the package to GitHub Packages
        run: dotnet nuget push ./nupkg/GraphXSDKClient.1.0.0.nupkg --source GitHubPackages --api-key ${{ secrets.GITHUB_TOKEN }}
