name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main  # Adjust the branch name as necessary

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Add GitHub Packages to NuGet sources
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -n GitHubPackages --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore DotnetStandardSDK/DotnetStandardSDK.sln

      - name: Build the solution
        run: dotnet build DotnetStandardSDK/DotnetStandardSDK.sln -c Release

      - name: Pack the NuGet package
        run: dotnet pack DotnetStandardSDK/DotnetStandardSDK/DotnetStandardSDK.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish the package to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source GitHubPackages --api-key ${{ secrets.GITHUB_TOKEN }}
